[project]
name = "syft-display-utils"
version = "0.1.0"
description = "Display utilities for syft-data-science"
readme = "README.md"
authors = [
    { name = "openmined", email = "info@openmined.org" }
]
requires-python = ">=3.9"
dependencies = [
    "loguru>=0.7.3",
    "pydantic>=2.10.6",
    "jinja2>=3.1.2",
    "rich>=14.0.0",
]

[project.scripts]
syft-display-utils = "syft_display_utils:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/syft_display_utils"]
only-include = ["src/syft_display_utils"]
exclude = ["src/syft_display_utils/**/__pycache__"]

[tool.hatch.build.targets.sdist]
only-include = ["src", "pyproject.toml", "README.md"]
exclude = ["src/**/__pycache__"]
