[project]
name = "syft-runtime"
version = "0.1.0"
description = "Runtime for Syft"
readme = "README.md"
authors = [
    { name = "openmined", email = "info@openmined.org" }
]
requires-python = ">=3.9"
dependencies = [
    "syft-rds>=0.1.3",
    "loguru>=0.7.3",
]

[project.scripts]
syft-runtime = "syft_runtime:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/syft_runtime"]
only-include = ["src/syft_runtime"]
exclude = ["src/syft_runtime/**/__pycache__"]

[tool.hatch.build.targets.sdist]
only-include = ["src", "pyproject.toml", "README.md"]
exclude = ["src/**/__pycache__"]

[tool.uv.sources]
syft-rds = { workspace = true }