# generated by datamodel-codegen:
#   filename:  addition.schema.json
#   timestamp: 2025-02-10T08:07:15+00:00

from __future__ import annotations

from pydantic import BaseModel


class Addition(BaseModel):
    a: int
    b: int
