[project]
name = "syft-rds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic[email]>=2.10.4",
    "typing-extensions>=4.12.2",
    "syft-core",
]

[tool.uv.sources]
syft-core = { git = "https://github.com/OpenMined/syft-extras.git", subdirectory = "packages/syft-core", branch = "main" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
