[project]
name = "syft-rds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipywidgets>=8.1.5",
    "pydantic[email]>=2.10.4",
    "syft-event",
    "typing-extensions>=4.12.2",
    "syft-runtime",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
syft-event = { git = "https://github.com/OpenMined/syft-extras.git", subdirectory = "packages/syft-event", rev = "main" }
syft-runtime = { workspace = true }

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "pip>=25.0",
]

[tool.uv.workspace]
members = ["../syft_runtime"]