[project]
name = "syft-rds"
version = "0.1.0"
description = "Remote data science on SyftBox"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic[email]>=2.10.4",
    "typing-extensions>=4.12.2",
    "loguru>=0.7.3",
    "syft-event>=0.1.0",
    "pyyaml>=6.0.2",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.4",
    "ipykernel>=6.29.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
