[project]
name = "syft-rds"
version = "0.1.4"
description = "Doing remote data science with SyftBox"
readme = "README.md"
authors = [{ name = "openmined", email = "info@openmined.org" }]
requires-python = ">=3.9"
dependencies = [
    "loguru>=0.7.3",
    "pydantic[email]>=2.10.4",
    "rich>=14.0.0",
    "syft-core>=0.2.8",
    "syft-event==0.2.8",
    "syft-rpc>=0.2.8",
    "typing-extensions>=4.14.0",
    "pyyaml>=6.0.2",
    "typer>=0.12.5",
    "jinja2>=3.1.6",
    "syft-runtimes",
    "syft-notebook-ui",
    "syft-datasets",
]

[project.scripts]
syft-rds = "syft_rds:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/syft_rds"]
only-include = ["src/syft_rds"]
exclude = ["src/syft_rds/**/__pycache__"]

[tool.hatch.build.targets.sdist]
only-include = ["src", "pyproject.toml", "README.md"]
exclude = ["src/**/__pycache__"]

[tool.uv.sources]
syft-datasets = { workspace = true }
syft-runtimes = { workspace = true }
syft-notebook-ui = { workspace = true }
