name: End-to-End Tests
on:
  pull_request:
    branches: [ main ]

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install uv
      run: |
        pip install uv
        
    - name: Set up test environment
      run: |
        cd rds
        just setup-test-env
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Run unit tests
      run: |
        cd rds
        just test-unit
        
    - name: Run E2E tests
      run: |
        cd rds
        just test-e2e
        
    - name: Run notebook tests
      run: |
        cd rds
        just test-notebooks 