name: PR Tests - RDS
on:
  workflow_dispatch:

  workflow_call:

  pull_request:
    branches:
      - main

concurrency:
  group: rds-${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || github.workflow_ref }}
  cancel-in-progress: true

jobs:
  call-pr-tests-rds-unit:
    uses: ./.github/workflows/pr-tests-base.yml
    with:
      test-type: test-rds-unit

  call-pr-tests-rds-integration:
    uses: ./.github/workflows/pr-tests-base.yml
    with:
      test-type: test-rds-integration

  # call-pr-tests-e2e:
  #   uses: ./.github/workflows/pr-tests-base.yml
  #   with:
  #     test-type: test-e2e
